version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
    command: yarn dev
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres/init.d:/docker-entrypoint-initdb.d
      - ./db/postgres/pgdata:/var/lib/postgresql/data
